import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import Header from "@/components/Header/header";
import "@studiocubics/styles/cubicscampaigns";
import "@studiocubics/core/styles";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cubics Campaigns",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Header />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
